version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11

jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo
steps:
  - checkout

  - run: cd client
  - run: yarn install

  - aws-s3/sync:
    from: build
    to: "s3://morninglights/"
    arguments: |
      --acl public-read \
      --cache-control "max-age=86400"
    overwrite: true
