version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/client
steps:
  - checkout

  - run: yarn install

  - aws-s3/sync:
    from: build
    to: "s3://morninglights/"
    arguments: |
      --acl public-read \
      --cache-control "max-age=86400"
    overwrite: true
